// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZdUcM6LhmeEt0Tm2etiWm_ZPyyIPaWjw',
    appId: '1:915949039498:web:9aade7d0f29177f0ce6273',
    messagingSenderId: '915949039498',
    projectId: 'flutter-ping-pong-game',
    authDomain: 'flutter-ping-pong-game.firebaseapp.com',
    storageBucket: 'flutter-ping-pong-game.firebasestorage.app',
    measurementId: 'G-TY2M4GPFDF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAX1S819dSHYXbB2T5UFl_c0hhaLIBd-vU',
    appId: '1:915949039498:android:d9d881e5ebad9133ce6273',
    messagingSenderId: '915949039498',
    projectId: 'flutter-ping-pong-game',
    storageBucket: 'flutter-ping-pong-game.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhiN861T6zNpcZczFMsvNBO2OdYkt8ioI',
    appId: '1:915949039498:ios:4f9cc7e8c0cfe17fce6273',
    messagingSenderId: '915949039498',
    projectId: 'flutter-ping-pong-game',
    storageBucket: 'flutter-ping-pong-game.firebasestorage.app',
    iosBundleId: 'com.example.pingPongGame',
  );
}
